name: Playwright Tests

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Or another supported version

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-playwright

      - name: Run Playwright tests
        run: pytest --tracing=retain-on-failure